# Generated by Django 6.0.4 on 2026-05-14 20:43

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Goal'), ('workout', 'Workout Frequency'), ('strength', 'Strength Goal')], max_length=20)),
                ('target_value', models.CharField(max_length=50)),
                ('current_value', models.CharField(blank=True, max_length=50)),
                ('deadline', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('primary_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility')], default='weight_loss', max_length=20)),
                ('workout_frequency', models.CharField(choices=[('1-2', '1-2 times per week'), ('3-4', '3-4 times per week'), ('5-6', '5-6 times per week'), ('7', 'Daily')], default='3-4', max_length=5)),
                ('body_fat', models.FloatField(blank=True, null=True)),
                ('muscle_mass', models.FloatField(blank=True, help_text='Muscle mass in kg', null=True)),
                ('starting_weight', models.FloatField(blank=True, null=True)),
                ('goal_weight', models.FloatField(blank=True, null=True)),
                ('membership_type', models.CharField(default='Premium', max_length=50)),
                ('membership_expiry', models.DateField(default=datetime.datetime(2027, 5, 14, 20, 43, 14, 957302, tzinfo=datetime.timezone.utc))),
                ('trainer_name', models.CharField(default='Lisa Wilson', max_length=100)),
                ('next_session', models.CharField(default='Next session: Tomorrow', max_length=100)),
                ('current_streak', models.IntegerField(default=0)),
                ('total_workouts', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(default=0.0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('goal_progress', models.IntegerField(default=0)),
                ('daily_calories', models.IntegerField(default=2200)),
                ('protein_goal', models.IntegerField(default=150)),
                ('carbs_goal', models.IntegerField(default=250)),
                ('fats_goal', models.IntegerField(default=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('workout_type', models.CharField(max_length=50)),
                ('duration', models.IntegerField(help_text='Minutes')),
                ('calories', models.IntegerField()),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workout_type', models.CharField(choices=[('cardio', 'Cardio & Endurance'), ('strength', 'Strength Training'), ('yoga', 'Yoga & Flexibility'), ('hiit', 'HIIT Training'), ('recovery', 'Active Recovery'), ('rest', 'Rest Day')], max_length=20)),
                ('exercises', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High')], max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
