# Generated by Django 4.2.28 on 2026-05-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_index=True, help_text='Unique identifier for the member', max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('membership', models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('STUDENT', 'Student')], default='BASIC', max_length=255)),
                ('join_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-join_date'],
                'indexes': [models.Index(fields=['member_id'], name='mainApp_mem_member__74c076_idx'), models.Index(fields=['status', 'membership'], name='mainApp_mem_status_b5fc22_idx')],
            },
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('trainer', models.CharField(help_text='Trainer name (can be replaced with FK later)', max_length=100)),
                ('start_time', models.DateTimeField(help_text='Date and time of the class')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time'], name='mainApp_gym_start_t_ba1bf4_idx'), models.Index(fields=['trainer'], name='mainApp_gym_trainer_3707c9_idx'), models.Index(fields=['name'], name='mainApp_gym_name_08364e_idx')],
            },
        ),
    ]
