# Generated by Django 6.0.4 on 2026-05-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_index=True, help_text='Unique identifier for the member', max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('membership', models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('STUDENT', 'Student')], default='BASIC', max_length=255)),
                ('join_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-join_date'],
                'indexes': [models.Index(fields=['member_id'], name='mainApp_mem_member__74c076_idx'), models.Index(fields=['status', 'membership'], name='mainApp_mem_status_b5fc22_idx')],
            },
        ),
    ]
