# Generated by Django 6.0.4 on 2026-05-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('trainer', models.CharField(help_text='Trainer name (can be replaced with FK later)', max_length=100)),
                ('start_time', models.DateTimeField(help_text='Date and time of the class')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time'], name='mainApp_gym_start_t_ba1bf4_idx'), models.Index(fields=['trainer'], name='mainApp_gym_trainer_3707c9_idx'), models.Index(fields=['name'], name='mainApp_gym_name_08364e_idx')],
            },
        ),
    ]
