# Generated by Django 6.0.4 on 2026-05-04 16:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the trainer', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('specialization', models.CharField(help_text="Trainer's area of expertise (e.g., Yoga, Cardio, Strength Training)", max_length=200)),
                ('email', models.EmailField(help_text="Trainer's email address", max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('phone', models.CharField(help_text="Trainer's contact number", max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('suspended', 'Suspended')], default='active', help_text='Current employment status', max_length=20)),
                ('profile_image', models.ImageField(blank=True, help_text="Trainer's profile picture", null=True, upload_to='trainers/profiles/')),
                ('bio', models.TextField(blank=True, help_text='Short biography or description', max_length=500, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Number of years of experience')),
                ('certifications', models.TextField(blank=True, help_text='List of certifications (comma-separated)', null=True)),
                ('hire_date', models.DateField(default=django.utils.timezone.now, help_text='Date when trainer was hired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trainer',
                'verbose_name_plural': 'Trainers',
                'db_table': 'trainers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='trainers_name_e764f5_idx'), models.Index(fields=['email'], name='trainers_email_bc045e_idx'), models.Index(fields=['status'], name='trainers_status_316368_idx'), models.Index(fields=['specialization'], name='trainers_special_a27a27_idx')],
            },
        ),
    ]
